version: '3.8'
services:
    php-apache:
        container_name: vsnippet-xss-dom-postmessage-21
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
