version: '3.8'
services:
    python-flask:
        container_name: vsnippet-xss-script-tag-4
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:1337
