version: '3.8'
services:
    php-apache:
        container_name: vsnippet-xss-string-outbreak-10
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
